name: prueba

# Evento
on:
  push:
    branches:
      - main

# Jobs
jobs:
  envio-sms:
    runs-on: ubuntu-latest

    steps:
      - name: Notificar a Slack en caso de éxito
        if: success()
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # Usamos 'payload' para enviar el mensaje en formato JSON
          payload: '{"text":"CI Pipeline complete!","channel":"#automatizacion-pruebas-prd"}'
          slack-message: 'Test run completed successfully'
          webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}  # URL del Webhook
