name: prueba

# Evento
on:
  push:
    branches:
      - mains

# Jobs
jobs:
  envio-sms:
    runs-on: ubuntu-latest

    steps:
      - name: Notificar a Slack en caso de éxito
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"CI Pipeline complete!","channel":"#automatizacion-pruebas-prd"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
